app.jwt.secret=mySuperSecretKeyForDevelopment123456789012345
spring.application.name=ElectroMart
spring.datasource.url=jdbc:mysql://localhost:3306/electromart
spring.datasource.username=root
spring.datasource.password=suraj
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8091
# CORS (Frontend ka URL dalo)
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:3000}